/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgument extends SimpleNode {

  public String name;

  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return this.name;
  }

}
/*
 * JavaCC - OriginalChecksum=fea525abc3189e0446a50e8bf3f4b561 (do not edit this
 * line)
 */
