/* Generated By:JJTree: Do not edit this line. ASTAssignmentLeft.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAssignmentLeft extends SimpleNode {
  public ASTAssignmentLeft(int id) {
    super(id);
  }

  public ASTAssignmentLeft(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return "=";
  }

}
/*
 * JavaCC - OriginalChecksum=71b872b08a81644cfa23742ed57e9ba0 (do not edit this
 * line)
 */
