/* Generated By:JJTree: Do not edit this line. ASTArryPosition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArryPosition extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTArryPosition(int id) {
    super(id);
  }

  public ASTArryPosition(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=0b48dc9efce46f961e9def49c871021e (do not edit this
 * line)
 */
