/* Generated By:JJTree: Do not edit this line. ASTAssignmentLeft.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignmentLeft extends SimpleNode {
  public ASTAssignmentLeft(int id) {
    super(id);
  }

  public ASTAssignmentLeft(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97946591a970e896ac8429312f5436b8 (do not edit this line) */
