/* Generated By:JJTree: Do not edit this line. ASTAT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAT extends SimpleNode {
  public ASTAT(int id) {
    super(id);
  }

  public ASTAT(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f04fb9dd4c9b573890eabb014b0d6fe (do not edit this line) */
