/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTbool extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=3f72c7a330452e52f662647e1b632b41 (do not edit this
 * line)
 */
