/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTClassDeclaration extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=34eb42b041b04eec7d3a1b3cb8b8b9ea (do not edit this
 * line)
 */
