/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {

  public String name = null;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(JavaMM p, int id) {
    super(p, id);
  }

  public String toString(){
    return name;
  }

}
/* JavaCC - OriginalChecksum=95efb57120f80cbb81fb8c6e9e80be0e (do not edit this line) */
