/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d54e90e9574c0ba90f90f011c3df026 (do not edit this line) */
