/* Generated By:JJTree: Do not edit this line. ASTExpressionLeftSubset.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionLeftSubset extends SimpleNode {
  public ASTExpressionLeftSubset(int id) {
    super(id);
  }

  public ASTExpressionLeftSubset(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5335d56f0f866dfd564dd6aa8b1bbb25 (do not edit this line) */
