/* Generated By:JJTree: Do not edit this line. ASTExpressionSubset.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionSubset extends SimpleNode {
  public ASTExpressionSubset(int id) {
    super(id);
  }

  public ASTExpressionSubset(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7fc606644bca2eb20aab192121e6d9b (do not edit this line) */
