/* Generated By:JJTree: Do not edit this line. ASTExpressionIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionIdent extends SimpleNode {

  public String name;

  public ASTExpressionIdent(int id) {
    super(id);
  }

  public ASTExpressionIdent(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return this.name;
  }

}
/*
 * JavaCC - OriginalChecksum=a04787ba25542a4b5c10d4f7c89e0f2e (do not edit this
 * line)
 */
