/* Generated By:JJTree: Do not edit this line. ASTExpressionSubset.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionSubset extends SimpleNode {

  public String name;

  public ASTExpressionSubset(int id) {
    super(id);
  }

  public ASTExpressionSubset(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return this.name;
  }

}
/*
 * JavaCC - OriginalChecksum=99a519075ab9d923c11e21d34b61bfd3 (do not edit this
 * line)
 */
