/* Generated By:JJTree: Do not edit this line. ASTExpressionLeft.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionLeft extends SimpleNode {
  public ASTExpressionLeft(int id) {
    super(id);
  }

  public ASTExpressionLeft(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3eccbbc38d0674da9ca108da5461dbd (do not edit this line) */
