/* Generated By:JJTree: Do not edit this line. ASTExpressionRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionRight extends SimpleNode {
  public ASTExpressionRight(int id) {
    super(id);
  }

  public ASTExpressionRight(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=863d1083ea5a8436cc7cadd2e8a51912 (do not edit this line) */
