/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e922cb8ab8dcfa8e608e147065d0e452 (do not edit this line) */
