/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElse extends SimpleNode {
  public ASTElse(int id) {
    super(id);
  }

  public ASTElse(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef62444199e6f0f234705a72f3bb76d6 (do not edit this line) */
