/* Generated By:JJTree: Do not edit this line. ASTExpressionTerminals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionTerminals extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTExpressionTerminals(int id) {
    super(id);
  }

  public ASTExpressionTerminals(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=cd87f927aca6fdbd006867d6ed53b27c (do not edit this
 * line)
 */
