/* Generated By:JJTree: Do not edit this line. ASTExpressionNoIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionNoIdent extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTExpressionNoIdent(int id) {
    super(id);
  }

  public ASTExpressionNoIdent(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=b3070f560cc6791d3bd97ba6c8e95221 (do not edit this
 * line)
 */
