/* Generated By:JJTree: Do not edit this line. ASTEndTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEndTerm extends SimpleNode {
  public ASTEndTerm(int id) {
    super(id);
  }

  public ASTEndTerm(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97105e703497d2b46db66c2c973581ec (do not edit this line) */
