/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTEQUAL extends SimpleNode {

  public String toString() {
    return "=";
  }

  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=1ad1094774383118414016267476a836 (do not edit this
 * line)
 */
