/* Generated By:JJTree: Do not edit this line. ASTEmpty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEmpty extends SimpleNode {
  public ASTEmpty(int id) {
    super(id);
  }

  public ASTEmpty(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eeed5d87de4fe0b512d017662cfcf557 (do not edit this line) */
