/* Generated By:JJTree: Do not edit this line. ASTFourthLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFourthLevelPrecende extends SimpleNode {
  public ASTFourthLevelPrecende(int id) {
    super(id);
  }

  public ASTFourthLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df8a33bf8f26681c7e13409eb4f7f38f (do not edit this line) */
