/* Generated By:JJTree: Do not edit this line. ASTFourthLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFourthLevelPrecende extends SimpleNode {
  public ASTFourthLevelPrecende(int id) {
    super(id);
  }

  public ASTFourthLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40e8caebd218b9557ee5d7c2f6371b3a (do not edit this line) */
