/* Generated By:JJTree: Do not edit this line. ASTFirstLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFirstLevelPrecende extends SimpleNode {
  public ASTFirstLevelPrecende(int id) {
    super(id);
  }

  public ASTFirstLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a65360bf33b1dce39960e8cb54bb78b (do not edit this line) */
