/* Generated By:JJTree: Do not edit this line. ASTFollowIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFollowIdentifier extends SimpleNode {
  public ASTFollowIdentifier(int id) {
    super(id);
  }

  public ASTFollowIdentifier(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=53c7da5063f9fbe56218d3a328802f36 (do not edit this line) */
