/* Generated By:JJTree: Do not edit this line. ASTIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIdent extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTIdent(int id) {
    super(id);
  }

  public ASTIdent(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=a09cf12fd30e87d2c2e3bd5cd82d73d4 (do not edit this
 * line)
 */
