/* Generated By:JJTree: Do not edit this line. ASTIdentifierStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifierStmt extends SimpleNode {
  public ASTIdentifierStmt(int id) {
    super(id);
  }

  public ASTIdentifierStmt(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf8fb4b20322a47c1e096d7136cc37fc (do not edit this line) */
