/* Generated By:JJTree: Do not edit this line. ASTIdentifierAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIdentifierAssignment extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTIdentifierAssignment(int id) {
    super(id);
  }

  public ASTIdentifierAssignment(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=b082364496ad6d326c36986e2894809c (do not edit this
 * line)
 */
