/* Generated By:JJTree: Do not edit this line. ASTIdentifierStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifierStmt extends SimpleNode {
  public ASTIdentifierStmt(int id) {
    super(id);
  }

  public ASTIdentifierStmt(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31337c810539eff631f283cb09f0a2cc (do not edit this line) */
