/* Generated By:JJTree: Do not edit this line. ASTinteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTinteger extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTinteger(int id) {
    super(id);
  }

  public ASTinteger(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=0146c49ed8439996aa68d74fd178cf40 (do not edit this
 * line)
 */
