/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c1626d71c6c9229618e9b4a9bcbc7929 (do not edit this line) */
