/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTnot extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=f45b6077a5ba97f4749835c860a327df (do not edit this
 * line)
 */
