/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79e107b556f9c4193dbc52ff917c5ed0 (do not edit this line) */
