/* Generated By:JJTree: Do not edit this line. ASTNewObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewObject extends SimpleNode {
  public ASTNewObject(int id) {
    super(id);
  }

  public ASTNewObject(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c1b388075acee7a35dc54674b665a15 (do not edit this line) */
