/* Generated By:JJTree: Do not edit this line. ASTNewObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewObject extends SimpleNode {
  public ASTNewObject(int id) {
    super(id);
  }

  public ASTNewObject(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11a06617c11aaf670f10f1784e761d1b (do not edit this line) */
