/* Generated By:JJTree: Do not edit this line. ASTnew_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTnew_ extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTnew_(int id) {
    super(id);
  }

  public ASTnew_(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=a7c3e9bf9c334aa0fe9fe2cf32367f88 (do not edit this
 * line)
 */
