/* Generated By:JJTree: Do not edit this line. ASTObjectAttr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTObjectAttr extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTObjectAttr(int id) {
    super(id);
  }

  public ASTObjectAttr(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=54faad4d55f0ec74015e3f98852f2c6d (do not edit this
 * line)
 */
