/* Generated By:JJTree: Do not edit this line. ASTOperatorPrecedence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperatorPrecedence extends SimpleNode {
  public ASTOperatorPrecedence(int id) {
    super(id);
  }

  public ASTOperatorPrecedence(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5178a183abc2d43777d22cda3021d045 (do not edit this line) */
