/* Generated By:JJTree: Do not edit this line. ASTOperator2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator2 extends SimpleNode {
  public ASTOperator2(int id) {
    super(id);
  }

  public ASTOperator2(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8590a81990243839bc1118620287b449 (do not edit this line) */
