/* Generated By:JJTree: Do not edit this line. ASTOperator3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator3 extends SimpleNode {
  public ASTOperator3(int id) {
    super(id);
  }

  public ASTOperator3(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0147c5711aece893ebae367b55e31ce7 (do not edit this line) */
