/* Generated By:JJTree: Do not edit this line. ASTOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator extends SimpleNode {
  public ASTOperator(int id) {
    super(id);
  }

  public ASTOperator(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a8acc565e6a4c51b91858997211fea4 (do not edit this line) */
