/* Generated By:JJTree: Do not edit this line. ASTOperator1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperator1 extends SimpleNode {
  public ASTOperator1(int id) {
    super(id);
  }

  public ASTOperator1(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b854491b20e5ada8297215df21de3eb (do not edit this line) */
