/* Generated By:JJTree: Do not edit this line. ASTObjectAttr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTObjectAttr extends SimpleNode {
  public ASTObjectAttr(int id) {
    super(id);
  }

  public ASTObjectAttr(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b16e33b47d725c9000b076e8a970324 (do not edit this line) */
