/* Generated By:JJTree: Do not edit this line. ASTPrecendeTerminals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTPrecendeTerminals extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTPrecendeTerminals(int id) {
    super(id);
  }

  public ASTPrecendeTerminals(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=860d7d9d84dea2e206095d2b35dcc852 (do not edit this
 * line)
 */
