/* Generated By:JJTree: Do not edit this line. ASTPositionAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTPositionAccess extends SimpleNode {
  public ASTPositionAccess(int id) {
    super(id);
  }

  public ASTPositionAccess(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return "[" + super.toString() + "]";
  }

}
/*
 * JavaCC - OriginalChecksum=2d37ffdf3fedc1b898156503159f5db8 (do not edit this
 * line)
 */
