/* Generated By:JJTree: Do not edit this line. ASTPositionAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPositionAccess extends SimpleNode {
  public ASTPositionAccess(int id) {
    super(id);
  }

  public ASTPositionAccess(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4b01bce560ea893a335206741a0c8d3 (do not edit this line) */
