/* Generated By:JJTree: Do not edit this line. ASTPOSITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTPOSITION extends SimpleNode {

  public String toString() {
    return ".at";
  }

  public ASTPOSITION(int id) {
    super(id);
  }

  public ASTPOSITION(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=0db8654b93a0910a86d1a2b43164aa05 (do not edit this
 * line)
 */
