/* Generated By:JJTree: Do not edit this line. ASTPrecedenceTerminals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTPrecedenceTerminals extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTPrecedenceTerminals(int id) {
    super(id);
  }

  public ASTPrecedenceTerminals(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=56b1b109c14c812aa5e6911b25bb70c5 (do not edit this
 * line)
 */
