/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTReturn extends SimpleNode {

  public String type = null;

  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=1d2c2d6d6e95be99fb0734dd04f06dc6 (do not edit this
 * line)
 */
