/* Generated By:JJTree: Do not edit this line. ASTRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRight extends SimpleNode {
  public ASTRight(int id) {
    super(id);
  }

  public ASTRight(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ef9fd990eb9a3ec2857c289eb5dd200 (do not edit this line) */
