/* Generated By:JJTree: Do not edit this line. ASTSecondLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSecondLevelPrecende extends SimpleNode {
  public ASTSecondLevelPrecende(int id) {
    super(id);
  }

  public ASTSecondLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d3f49952cb66b47a546feaccdca4460 (do not edit this line) */
