/* Generated By:JJTree: Do not edit this line. ASTSecondLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSecondLevelPrecende extends SimpleNode {
  public ASTSecondLevelPrecende(int id) {
    super(id);
  }

  public ASTSecondLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f218aba52791ecd79b897e04774d9321 (do not edit this line) */
