/* Generated By:JJTree: Do not edit this line. ASTSymbol.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSymbol extends SimpleNode {
  public ASTSymbol(int id) {
    super(id);
  }

  public ASTSymbol(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9523ed0bc1492866beb4dc0fb8edeaa7 (do not edit this line) */
