/* Generated By:JJTree: Do not edit this line. ASTthis_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTthis_ extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTthis_(int id) {
    super(id);
  }

  public ASTthis_(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=60cd7158388b57d23f43fe8a8596ceaa (do not edit this
 * line)
 */
