/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTType extends SimpleNode {

  public String type;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(JavaMM p, int id) {
    super(p, id);
  }

  public String toString() {
    return this.type;
  }

}
/*
 * JavaCC - OriginalChecksum=cdfb17f5d325e9e6af036179ee814acb (do not edit this
 * line)
 */
