/* Generated By:JJTree: Do not edit this line. ASTThirdLevelPrecende.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThirdLevelPrecende extends SimpleNode {
  public ASTThirdLevelPrecende(int id) {
    super(id);
  }

  public ASTThirdLevelPrecende(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=441c7c7815ace5f114ad332cd88c92b4 (do not edit this line) */
