/* Generated By:JJTree: Do not edit this line. ASTtest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTtest extends SimpleNode {

  public String name;

  public String toString() {
    return name;
  }

  public ASTtest(int id) {
    super(id);
  }

  public ASTtest(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=502c13fc07bc20a334bb3a3cb1c076d3 (do not edit this
 * line)
 */
