/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTTerm extends SimpleNode {

  public String name;

  public String toString() {
    return this.name;
  }

  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(JavaMM p, int id) {
    super(p, id);
  }

}
/*
 * JavaCC - OriginalChecksum=743af70d164fe9c9d4632baebabfe4a5 (do not edit this
 * line)
 */
