/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {


  public String type = null;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(JavaMM p, int id) {
    super(p, id);
  }

  public String toString(){
    return type;
  }

}
/* JavaCC - OriginalChecksum=5246da2fc2102998efd8c9484f045157 (do not edit this line) */
