/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration extends SimpleNode {


  public String name;

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(JavaMM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a09ee6b8c300365dd2b6697eefd7709c (do not edit this line) */
