/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 5.0 */
public interface JavaMMTreeConstants
{
  public int JJTCLASSDECLARATION = 0;
  public int JJTMETHODDECLARATION = 1;
  public int JJTMAINDECLARATION = 2;
  public int JJTEMPTY = 3;
  public int JJTFUNCTIONBODY = 4;
  public int JJTTYPE = 5;
  public int JJTVARDECLARATION = 6;
  public int JJTSTATEMENT = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTPOSITIONACCESS = 9;
  public int JJTASSIGNMENTLEFT = 10;
  public int JJTSYMBOL = 11;
  public int JJTEXPRESSION = 12;
  public int JJTNEWOBJECT = 13;
  public int JJTOBJECTATTR = 14;
  public int JJTEXPRESSIONLEFT = 15;


  public String[] jjtNodeName = {
    "ClassDeclaration",
    "MethodDeclaration",
    "MainDeclaration",
    "Empty",
    "FunctionBody",
    "Type",
    "VarDeclaration",
    "Statement",
    "Assignment",
    "PositionAccess",
    "AssignmentLeft",
    "Symbol",
    "Expression",
    "NewObject",
    "ObjectAttr",
    "ExpressionLeft",
  };
}
/* JavaCC - OriginalChecksum=4340e80a5e434161068343a337361f96 (do not edit this line) */
