/* Generated By:JJTree&JavaCC: Do not edit this line. JavaMMConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaMMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int TYPEINT = 8;
  /** RegularExpression Id. */
  int TYPESTRING = 9;
  /** RegularExpression Id. */
  int TYPEBOOLEAN = 10;
  /** RegularExpression Id. */
  int PUBLIC = 11;
  /** RegularExpression Id. */
  int STATIC = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int MAIN = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int LENGTH = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int THIS = 23;
  /** RegularExpression Id. */
  int NEW = 24;
  /** RegularExpression Id. */
  int SMALLERSIGN = 25;
  /** RegularExpression Id. */
  int PLUSSIGN = 26;
  /** RegularExpression Id. */
  int MINUSIGN = 27;
  /** RegularExpression Id. */
  int TIMESSIGN = 28;
  /** RegularExpression Id. */
  int DIVIDESIGN = 29;
  /** RegularExpression Id. */
  int LOGICAND = 30;
  /** RegularExpression Id. */
  int LOGICNOT = 31;
  /** RegularExpression Id. */
  int OPENCURLYBRACKET = 32;
  /** RegularExpression Id. */
  int CLOSECURLYBRACKET = 33;
  /** RegularExpression Id. */
  int OPENBRACKET = 34;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int PARENTHESISOPEN = 37;
  /** RegularExpression Id. */
  int PARENTHESISCLOSE = 38;
  /** RegularExpression Id. */
  int COMMA = 39;
  /** RegularExpression Id. */
  int POINT = 40;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 41;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 42;
  /** RegularExpression Id. */
  int HEX_LITERAL = 43;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 44;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER>",
    "\"class\"",
    "\"extends\"",
    "\"int\"",
    "\"String\"",
    "\"boolean\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"=\"",
    "\"true\"",
    "\"length\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
  };

}
