/* Generated By:JavaCC: Do not edit this line. JavaMMConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaMMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int ARSym = 6;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int EXTENDS = 8;
  /** RegularExpression Id. */
  int TYPEINT = 9;
  /** RegularExpression Id. */
  int TYPEBOOLEAN = 10;
  /** RegularExpression Id. */
  int PUBLIC = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int OPENCURLYBRACKET = 13;
  /** RegularExpression Id. */
  int CLOSECURLYBRACKET = 14;
  /** RegularExpression Id. */
  int OPENBRACKET = 15;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int PARENTHESISOPEN = 18;
  /** RegularExpression Id. */
  int PARENTHESISCLOSE = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER>",
    "<ARSym>",
    "\"class\"",
    "\"extends\"",
    "\"int\"",
    "\"boolean\"",
    "\"public\"",
    "\"return\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<IDENTIFIER>",
  };

}
