/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 5.0 */
public interface JavaMMTreeConstants
{
  public int JJTCLASSDECLARATION = 0;
  public int JJTVOID = 1;
  public int JJTMETHODDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTRETURN = 4;
  public int JJTARGUMENTS = 5;
  public int JJTARGUMENT = 6;
  public int JJTFUNCTIONBODY = 7;
  public int JJTTYPE = 8;
  public int JJTVARDECLARATION = 9;
  public int JJTIF = 10;
  public int JJTELSE = 11;
  public int JJTASSIGNMENT = 12;
  public int JJTWHILE = 13;
  public int JJTPOSITIONACCESS = 14;
  public int JJTASSIGNMENTLEFT = 15;
  public int JJTNEWOBJECT = 16;
  public int JJTOBJECTATTR = 17;
  public int JJTEXPRESSIONIDENT = 18;
  public int JJTEXPRESSIONSUBSET = 19;
  public int JJTLENGTH = 20;
  public int JJTOPERATOR = 21;
  public int JJTFIRSTLEVELPRECENDE = 22;
  public int JJTSECONDLEVELPRECENDE = 23;
  public int JJTTHIRDLEVELPRECENDE = 24;
  public int JJTFOURTHLEVELPRECENDE = 25;


  public String[] jjtNodeName = {
    "ClassDeclaration",
    "void",
    "MethodDeclaration",
    "MainDeclaration",
    "Return",
    "Arguments",
    "Argument",
    "FunctionBody",
    "Type",
    "VarDeclaration",
    "If",
    "Else",
    "Assignment",
    "While",
    "PositionAccess",
    "AssignmentLeft",
    "NewObject",
    "ObjectAttr",
    "ExpressionIdent",
    "ExpressionSubset",
    "Length",
    "Operator",
    "FirstLevelPrecende",
    "SecondLevelPrecende",
    "ThirdLevelPrecende",
    "FourthLevelPrecende",
  };
}
/* JavaCC - OriginalChecksum=934f5ff3e86038cb53784fd40f6aad5c (do not edit this line) */
