/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTBool extends SimpleNode {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e319ba42429a2dcb1d0230a58572b537 (do not edit this line) */
