/* Generated By:JJTree: Do not edit this line. ASTFunctionBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTFunctionBody extends SimpleNode {
  public ASTFunctionBody(int id) {
    super(id);
  }

  public ASTFunctionBody(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c94631100ad293d0bbab67900b35140a (do not edit this line) */
