/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTMainDeclaration extends SimpleNode {
  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d333e45844ba4e43c0ee2117f721f1e7 (do not edit this line) */
