/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTnot extends SimpleNode {
  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1eef74f491f8d9fc3bf335df3c2da070 (do not edit this line) */
