/* Generated By:JJTree: Do not edit this line. ASTNew.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTNew extends SimpleNode {
  public ASTNew(int id) {
    super(id);
  }

  public ASTNew(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5fcdd3691ee673fc6f4385ba83b40239 (do not edit this line) */
