/* Generated By:JJTree: Do not edit this line. ASTObjectAttr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTObjectAttr extends SimpleNode {
  public ASTObjectAttr(int id) {
    super(id);
  }

  public ASTObjectAttr(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=837297a3211ac2072492faa72f75f073 (do not edit this line) */
