/* Generated By:JJTree: Do not edit this line. ASTPoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTPoint extends SimpleNode {
  public ASTPoint(int id) {
    super(id);
  }

  public ASTPoint(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e9b40f059b6643f641750dccd9d49237 (do not edit this line) */
