/* Generated By:JJTree: Do not edit this line. ASTPosition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTPosition extends SimpleNode {
  public ASTPosition(int id) {
    super(id);
  }

  public ASTPosition(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5f2ca24879385d560f93776259a46e6 (do not edit this line) */
