/* Generated By:JJTree: Do not edit this line. ASTThis_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

public
class ASTThis_ extends SimpleNode {
  public ASTThis_(int id) {
    super(id);
  }

  public ASTThis_(jmm_parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bcb8125202e629c46b5f66f18cdd2c7e (do not edit this line) */
