/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=521ddcd8bd7a8580f6d1249dae8e9275 (do not edit this line) */
