/* Generated By:JJTree: Do not edit this line. ASTFunctionBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionBody extends SimpleNode {
  public ASTFunctionBody(int id) {
    super(id);
  }

  public ASTFunctionBody(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=345ba9829693df297e6583e48c83550f (do not edit this line) */
