/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fba93c94d456306d999a212f574ab146 (do not edit this line) */
