/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06ca8ed88715a86ae0804bfe4c26833d (do not edit this line) */
