/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnot extends SimpleNode {
  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5993e945db61a413817269fdadfc675 (do not edit this line) */
