/* Generated By:JJTree: Do not edit this line. ASTNew.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNew extends SimpleNode {
  public ASTNew(int id) {
    super(id);
  }

  public ASTNew(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96dcb5d41a89c06576f392150f3541a2 (do not edit this line) */
