/* Generated By:JJTree: Do not edit this line. ASTPoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPoint extends SimpleNode {
  public ASTPoint(int id) {
    super(id);
  }

  public ASTPoint(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c51829160cb04d35e5c52232600465e (do not edit this line) */
