/* Generated By:JJTree: Do not edit this line. ASTPosition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPosition extends SimpleNode {
  public ASTPosition(int id) {
    super(id);
  }

  public ASTPosition(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=13000ccc5322ba340586b65eefae02b3 (do not edit this line) */
