/* Generated By:JJTree: Do not edit this line. ASTThis_.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThis_ extends SimpleNode {
  public ASTThis_(int id) {
    super(id);
  }

  public ASTThis_(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30aeed1e932cb799ce7b7cbd34b2260a (do not edit this line) */
