/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 5.0 */
public interface jmmTreeConstants
{
  public int JJTCLASSDECLARATION = 0;
  public int JJTVOID = 1;
  public int JJTMETHODDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTRETURN = 4;
  public int JJTARGUMENTS = 5;
  public int JJTARGUMENT = 6;
  public int JJTFUNCTIONBODY = 7;
  public int JJTTYPE = 8;
  public int JJTVARDECLARATION = 9;
  public int JJTINTEGER = 10;
  public int JJTBOOL = 11;
  public int JJTTHIS_ = 12;
  public int JJTNOT = 13;
  public int JJTEQUAL = 14;
  public int JJTAND = 15;
  public int JJTLESSTHAN = 16;
  public int JJTADD = 17;
  public int JJTSUB = 18;
  public int JJTMULT = 19;
  public int JJTDIV = 20;
  public int JJTTERM = 21;
  public int JJTIF = 22;
  public int JJTELSE = 23;
  public int JJTWHILE = 24;
  public int JJTPOINT = 25;
  public int JJTPOSITION = 26;
  public int JJTNEW = 27;
  public int JJTOBJECTATTR = 28;
  public int JJTLENGTH = 29;


  public String[] jjtNodeName = {
    "ClassDeclaration",
    "void",
    "MethodDeclaration",
    "MainDeclaration",
    "Return",
    "Arguments",
    "Argument",
    "FunctionBody",
    "Type",
    "VarDeclaration",
    "Integer",
    "Bool",
    "This_",
    "not",
    "Equal",
    "And",
    "LessThan",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Term",
    "If",
    "Else",
    "While",
    "Point",
    "Position",
    "New",
    "ObjectAttr",
    "Length",
  };
}
/* JavaCC - OriginalChecksum=76ae01519bb9e7f906de91cfc3046367 (do not edit this line) */
